import { Polter, Booking } from './types';

export const mockPolter: Polter[] = [
  {
    id: 'p1',
    name: 'Polter Waldweg Nord',
    sortiment: 'Fichte Langholz',
    volumen: 85.4,
    beschreibung: 'Langholz an der Forststraße, gut zugänglich für LKW',
    lat: 48.1351,
    lng: 11.582,
    eudrNummer: 'EUDR-2026-001',
    status: 'Bereit',
    forstbetrieb: 'Forstbetrieb Müller',
    transporteurId: 't1',
    transporteurName: 'Spedition Huber',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Berger',
    erstelltAm: '2026-02-15T08:30:00Z',
  },
  {
    id: 'p2',
    name: 'Polter Hangkante Süd',
    sortiment: 'Buche Stammholz',
    volumen: 42.0,
    beschreibung: 'Stammholz am Hangfuß, Zufahrt über Schotterweg',
    lat: 48.14,
    lng: 11.57,
    eudrNummer: 'EUDR-2026-002',
    status: 'Transport zugewiesen',
    forstbetrieb: 'Forstbetrieb Müller',
    transporteurId: 't1',
    transporteurName: 'Spedition Huber',
    kaeuferId: null,
    kaeuferName: null,
    erstelltAm: '2026-02-20T10:00:00Z',
  },
  {
    id: 'p3',
    name: 'Polter Kreuzung B12',
    sortiment: 'Kiefer Industrieholz',
    volumen: 120.8,
    beschreibung: 'Industrieholz direkt an der Bundesstraße',
    lat: 48.125,
    lng: 11.595,
    eudrNummer: 'EUDR-2026-003',
    status: 'Neu',
    forstbetrieb: 'Forstbetrieb Müller',
    transporteurId: null,
    transporteurName: null,
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Berger',
    erstelltAm: '2026-03-01T14:15:00Z',
  },
  {
    id: 'p4',
    name: 'Polter Bachbrücke',
    sortiment: 'Eiche Wertholz',
    volumen: 18.5,
    beschreibung: 'Wertholz nahe Bachbrücke, trocken gelagert',
    lat: 48.145,
    lng: 11.56,
    eudrNummer: 'EUDR-2026-004',
    status: 'Abgeholt',
    forstbetrieb: 'Forstbetrieb Müller',
    transporteurId: 't1',
    transporteurName: 'Spedition Huber',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Berger',
    erstelltAm: '2026-01-10T09:00:00Z',
  },
  {
    id: 'p5',
    name: 'Polter Lichtung West',
    sortiment: 'Fichte Langholz',
    volumen: 65.0,
    beschreibung: 'Frisch geschlagen, auf Lichtung gelagert',
    lat: 48.13,
    lng: 11.55,
    eudrNummer: 'EUDR-2026-005',
    status: 'Geliefert',
    forstbetrieb: 'Forstbetrieb Müller',
    transporteurId: 't1',
    transporteurName: 'Spedition Huber',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Berger',
    erstelltAm: '2025-12-20T07:45:00Z',
  },
];

export const mockBookings: Booking[] = [
  { id: 'bk1', polterId: 'p1', typ: 'checkin', menge: 50.2, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2026-02-15T09:00:00Z' },
  { id: 'bk2', polterId: 'p1', typ: 'checkin', menge: 35.2, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2026-02-18T11:30:00Z' },
  { id: 'bk3', polterId: 'p2', typ: 'checkin', menge: 42.0, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2026-02-20T10:30:00Z' },
  { id: 'bk4', polterId: 'p3', typ: 'checkin', menge: 120.8, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2026-03-01T14:30:00Z' },
  { id: 'bk5', polterId: 'p4', typ: 'checkin', menge: 18.5, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2026-01-10T09:30:00Z' },
  { id: 'bk6', polterId: 'p4', typ: 'checkout', menge: 18.5, fotoUrl: null, erstelltVon: 'Spedition Huber', erstelltAm: '2026-02-25T06:00:00Z' },
  { id: 'bk7', polterId: 'p5', typ: 'checkin', menge: 65.0, fotoUrl: null, erstelltVon: 'Förster Müller', erstelltAm: '2025-12-20T08:00:00Z' },
  { id: 'bk8', polterId: 'p5', typ: 'checkout', menge: 65.0, fotoUrl: null, erstelltVon: 'Spedition Huber', erstelltAm: '2026-01-15T07:00:00Z' },
];

export const sortimentOptions = [
  'Fichte Langholz',
  'Fichte Kurzholz',
  'Buche Stammholz',
  'Eiche Wertholz',
  'Kiefer Industrieholz',
  'Lärche Bauholz',
  'Energieholz',
];

export const transporteure = [
  { id: 't1', name: 'Spedition Huber' },
  { id: 't2', name: 'Transport Meier' },
  { id: 't3', name: 'Holzfuhren Schmid' },
];

export const kaeufer = [
  { id: 'b1', name: 'Sägewerk Berger' },
  { id: 'b2', name: 'Holzhandel Wagner' },
  { id: 'b3', name: 'Biomasse GmbH' },
];
