import { Polter, Booking } from './types';

export const mockPolter: Polter[] = [
  {
    id: 'p1',
    name: 'Polter Heitersberg',
    sortiment: 'Fichte Langholz',
    volumen: 85.4,
    beschreibung: 'Langholz an der Forststrasse, gut zugänglich für LKW',
    lat: 47.4085,
    lng: 8.2935,
    eudrNummer: 'EUDR-2026-001',
    status: 'Bereit',
    forstbetrieb: 'Forstbetrieb Wettingen',
    transporteurId: 't1',
    transporteurName: 'Transport Frey AG',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Villiger',
    erstelltAm: '2026-02-15T08:30:00Z',
  },
  {
    id: 'p2',
    name: 'Polter Baregg Süd',
    sortiment: 'Buche Stammholz',
    volumen: 42.0,
    beschreibung: 'Stammholz am Hangfuss, Zufahrt über Schotterweg',
    lat: 47.4215,
    lng: 8.3120,
    eudrNummer: 'EUDR-2026-002',
    status: 'Transport zugewiesen',
    forstbetrieb: 'Forstbetrieb Wettingen',
    transporteurId: 't1',
    transporteurName: 'Transport Frey AG',
    kaeuferId: null,
    kaeuferName: null,
    erstelltAm: '2026-02-20T10:00:00Z',
  },
  {
    id: 'p3',
    name: 'Polter Lenzburg Wald',
    sortiment: 'Kiefer Industrieholz',
    volumen: 120.8,
    beschreibung: 'Industrieholz direkt an der Kantonsstrasse',
    lat: 47.3884,
    lng: 8.1756,
    eudrNummer: 'EUDR-2026-003',
    status: 'Neu',
    forstbetrieb: 'Forstbetrieb Wettingen',
    transporteurId: null,
    transporteurName: null,
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Villiger',
    erstelltAm: '2026-03-01T14:15:00Z',
  },
  {
    id: 'p4',
    name: 'Polter Bremgarten Reuss',
    sortiment: 'Eiche Wertholz',
    volumen: 18.5,
    beschreibung: 'Wertholz nahe Reussbrücke, trocken gelagert',
    lat: 47.3507,
    lng: 8.3427,
    eudrNummer: 'EUDR-2026-004',
    status: 'Abgeholt',
    forstbetrieb: 'Forstbetrieb Wettingen',
    transporteurId: 't1',
    transporteurName: 'Transport Frey AG',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Villiger',
    erstelltAm: '2026-01-10T09:00:00Z',
  },
  {
    id: 'p5',
    name: 'Polter Rohr Lichtung',
    sortiment: 'Fichte Langholz',
    volumen: 65.0,
    beschreibung: 'Frisch geschlagen, auf Lichtung gelagert',
    lat: 47.4002,
    lng: 8.0536,
    eudrNummer: 'EUDR-2026-005',
    status: 'Geliefert',
    forstbetrieb: 'Forstbetrieb Wettingen',
    transporteurId: 't1',
    transporteurName: 'Transport Frey AG',
    kaeuferId: 'b1',
    kaeuferName: 'Sägewerk Villiger',
    erstelltAm: '2025-12-20T07:45:00Z',
  },
];

export const mockBookings: Booking[] = [
  { id: 'bk1', polterId: 'p1', typ: 'checkin', menge: 50.2, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2026-02-15T09:00:00Z' },
  { id: 'bk2', polterId: 'p1', typ: 'checkin', menge: 35.2, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2026-02-18T11:30:00Z' },
  { id: 'bk3', polterId: 'p2', typ: 'checkin', menge: 42.0, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2026-02-20T10:30:00Z' },
  { id: 'bk4', polterId: 'p3', typ: 'checkin', menge: 120.8, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2026-03-01T14:30:00Z' },
  { id: 'bk5', polterId: 'p4', typ: 'checkin', menge: 18.5, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2026-01-10T09:30:00Z' },
  { id: 'bk6', polterId: 'p4', typ: 'checkout', menge: 18.5, fotoUrl: null, erstelltVon: 'Transport Frey AG', erstelltAm: '2026-02-25T06:00:00Z' },
  { id: 'bk7', polterId: 'p5', typ: 'checkin', menge: 65.0, fotoUrl: null, erstelltVon: 'Förster Meier', erstelltAm: '2025-12-20T08:00:00Z' },
  { id: 'bk8', polterId: 'p5', typ: 'checkout', menge: 65.0, fotoUrl: null, erstelltVon: 'Transport Frey AG', erstelltAm: '2026-01-15T07:00:00Z' },
];

export const sortimentOptions = [
  'Fichte Langholz',
  'Fichte Kurzholz',
  'Buche Stammholz',
  'Eiche Wertholz',
  'Kiefer Industrieholz',
  'Lärche Bauholz',
  'Energieholz',
];
